namespace GooglePlayGames.Native
{
	internal class NativeQuestClient : global::GooglePlayGames.BasicApi.Quests.IQuestsClient
	{
		private readonly global::GooglePlayGames.Native.PInvoke.QuestManager mManager;

		internal NativeQuestClient(global::GooglePlayGames.Native.PInvoke.QuestManager manager)
		{
			mManager = global::GooglePlayGames.OurUtils.Misc.CheckNotNull(manager);
		}

		public void Fetch(global::GooglePlayGames.BasicApi.DataSource source, string questId, global::System.Action<global::GooglePlayGames.BasicApi.ResponseStatus, global::GooglePlayGames.BasicApi.Quests.IQuest> callback)
		{
			global::GooglePlayGames.OurUtils.Misc.CheckNotNull(questId);
			global::GooglePlayGames.OurUtils.Misc.CheckNotNull(callback);
			callback = global::GooglePlayGames.Native.CallbackUtils.ToOnGameThread(callback);
			mManager.Fetch(global::GooglePlayGames.Native.ConversionUtils.AsDataSource(source), questId, delegate(global::GooglePlayGames.Native.PInvoke.QuestManager.FetchResponse response)
			{
				global::GooglePlayGames.BasicApi.ResponseStatus arg = global::GooglePlayGames.Native.ConversionUtils.ConvertResponseStatus(response.ResponseStatus());
				if (!response.RequestSucceeded())
				{
					callback(arg, null);
				}
				else
				{
					callback(arg, response.Data());
				}
			});
		}

		public void FetchMatchingState(global::GooglePlayGames.BasicApi.DataSource source, global::GooglePlayGames.BasicApi.Quests.QuestFetchFlags flags, global::System.Action<global::GooglePlayGames.BasicApi.ResponseStatus, global::System.Collections.Generic.List<global::GooglePlayGames.BasicApi.Quests.IQuest>> callback)
		{
			global::GooglePlayGames.OurUtils.Misc.CheckNotNull(callback);
			callback = global::GooglePlayGames.Native.CallbackUtils.ToOnGameThread(callback);
			mManager.FetchList(global::GooglePlayGames.Native.ConversionUtils.AsDataSource(source), (int)flags, delegate(global::GooglePlayGames.Native.PInvoke.QuestManager.FetchListResponse response)
			{
				global::GooglePlayGames.BasicApi.ResponseStatus arg = global::GooglePlayGames.Native.ConversionUtils.ConvertResponseStatus(response.ResponseStatus());
				if (!response.RequestSucceeded())
				{
					callback(arg, null);
				}
				else
				{
					callback(arg, global::System.Linq.Enumerable.ToList(global::System.Linq.Enumerable.Cast<global::GooglePlayGames.BasicApi.Quests.IQuest>(response.Data())));
				}
			});
		}

		public void ShowAllQuestsUI(global::System.Action<global::GooglePlayGames.BasicApi.Quests.QuestUiResult, global::GooglePlayGames.BasicApi.Quests.IQuest, global::GooglePlayGames.BasicApi.Quests.IQuestMilestone> callback)
		{
			global::GooglePlayGames.OurUtils.Misc.CheckNotNull(callback);
			callback = global::GooglePlayGames.Native.CallbackUtils.ToOnGameThread(callback);
			mManager.ShowAllQuestUI(FromQuestUICallback(callback));
		}

		public void ShowSpecificQuestUI(global::GooglePlayGames.BasicApi.Quests.IQuest quest, global::System.Action<global::GooglePlayGames.BasicApi.Quests.QuestUiResult, global::GooglePlayGames.BasicApi.Quests.IQuest, global::GooglePlayGames.BasicApi.Quests.IQuestMilestone> callback)
		{
			global::GooglePlayGames.OurUtils.Misc.CheckNotNull(quest);
			global::GooglePlayGames.OurUtils.Misc.CheckNotNull(callback);
			callback = global::GooglePlayGames.Native.CallbackUtils.ToOnGameThread(callback);
			global::GooglePlayGames.Native.PInvoke.NativeQuest nativeQuest = quest as global::GooglePlayGames.Native.PInvoke.NativeQuest;
			if (nativeQuest == null)
			{
				global::GooglePlayGames.OurUtils.Logger.e("Encountered quest that was not generated by this IQuestClient");
				callback(global::GooglePlayGames.BasicApi.Quests.QuestUiResult.BadInput, null, null);
			}
			else
			{
				mManager.ShowQuestUI(nativeQuest, FromQuestUICallback(callback));
			}
		}

		private static global::GooglePlayGames.BasicApi.Quests.QuestUiResult UiErrorToQuestUiResult(global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.UIStatus status)
		{
			switch (status)
			{
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.UIStatus.ERROR_INTERNAL:
				return global::GooglePlayGames.BasicApi.Quests.QuestUiResult.InternalError;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.UIStatus.ERROR_NOT_AUTHORIZED:
				return global::GooglePlayGames.BasicApi.Quests.QuestUiResult.NotAuthorized;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.UIStatus.ERROR_CANCELED:
				return global::GooglePlayGames.BasicApi.Quests.QuestUiResult.UserCanceled;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.UIStatus.ERROR_VERSION_UPDATE_REQUIRED:
				return global::GooglePlayGames.BasicApi.Quests.QuestUiResult.VersionUpdateRequired;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.UIStatus.ERROR_TIMEOUT:
				return global::GooglePlayGames.BasicApi.Quests.QuestUiResult.Timeout;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.UIStatus.ERROR_UI_BUSY:
				return global::GooglePlayGames.BasicApi.Quests.QuestUiResult.UiBusy;
			default:
				global::GooglePlayGames.OurUtils.Logger.e("Unknown error status: " + status);
				return global::GooglePlayGames.BasicApi.Quests.QuestUiResult.InternalError;
			}
		}

		private static global::System.Action<global::GooglePlayGames.Native.PInvoke.QuestManager.QuestUIResponse> FromQuestUICallback(global::System.Action<global::GooglePlayGames.BasicApi.Quests.QuestUiResult, global::GooglePlayGames.BasicApi.Quests.IQuest, global::GooglePlayGames.BasicApi.Quests.IQuestMilestone> callback)
		{
			return delegate(global::GooglePlayGames.Native.PInvoke.QuestManager.QuestUIResponse response)
			{
				if (!response.RequestSucceeded())
				{
					callback(UiErrorToQuestUiResult(response.RequestStatus()), null, null);
				}
				else
				{
					global::GooglePlayGames.Native.PInvoke.NativeQuest nativeQuest = response.AcceptedQuest();
					global::GooglePlayGames.Native.PInvoke.NativeQuestMilestone nativeQuestMilestone = response.MilestoneToClaim();
					if (nativeQuest != null)
					{
						callback(global::GooglePlayGames.BasicApi.Quests.QuestUiResult.UserRequestsQuestAcceptance, nativeQuest, null);
						nativeQuestMilestone.Dispose();
					}
					else if (nativeQuestMilestone != null)
					{
						callback(global::GooglePlayGames.BasicApi.Quests.QuestUiResult.UserRequestsMilestoneClaiming, null, response.MilestoneToClaim());
						nativeQuest.Dispose();
					}
					else
					{
						global::GooglePlayGames.OurUtils.Logger.e("Quest UI succeeded without a quest acceptance or milestone claim.");
						nativeQuest.Dispose();
						nativeQuestMilestone.Dispose();
						callback(global::GooglePlayGames.BasicApi.Quests.QuestUiResult.InternalError, null, null);
					}
				}
			};
		}

		public void Accept(global::GooglePlayGames.BasicApi.Quests.IQuest quest, global::System.Action<global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus, global::GooglePlayGames.BasicApi.Quests.IQuest> callback)
		{
			global::GooglePlayGames.OurUtils.Misc.CheckNotNull(quest);
			global::GooglePlayGames.OurUtils.Misc.CheckNotNull(callback);
			callback = global::GooglePlayGames.Native.CallbackUtils.ToOnGameThread(callback);
			global::GooglePlayGames.Native.PInvoke.NativeQuest nativeQuest = quest as global::GooglePlayGames.Native.PInvoke.NativeQuest;
			if (nativeQuest == null)
			{
				global::GooglePlayGames.OurUtils.Logger.e("Encountered quest that was not generated by this IQuestClient");
				callback(global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.BadInput, null);
				return;
			}
			mManager.Accept(nativeQuest, delegate(global::GooglePlayGames.Native.PInvoke.QuestManager.AcceptResponse response)
			{
				if (response.RequestSucceeded())
				{
					callback(global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.Success, response.AcceptedQuest());
				}
				else
				{
					callback(FromAcceptStatus(response.ResponseStatus()), null);
				}
			});
		}

		private static global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus FromAcceptStatus(global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestAcceptStatus status)
		{
			switch (status)
			{
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestAcceptStatus.ERROR_INTERNAL:
				return global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.InternalError;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestAcceptStatus.ERROR_NOT_AUTHORIZED:
				return global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.NotAuthorized;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestAcceptStatus.ERROR_QUEST_NOT_STARTED:
				return global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.QuestNotStarted;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestAcceptStatus.ERROR_QUEST_NO_LONGER_AVAILABLE:
				return global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.QuestNoLongerAvailable;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestAcceptStatus.ERROR_TIMEOUT:
				return global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.Timeout;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestAcceptStatus.VALID:
				return global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.Success;
			default:
				global::GooglePlayGames.OurUtils.Logger.e("Encountered unknown status: " + status);
				return global::GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.InternalError;
			}
		}

		public void ClaimMilestone(global::GooglePlayGames.BasicApi.Quests.IQuestMilestone milestone, global::System.Action<global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus, global::GooglePlayGames.BasicApi.Quests.IQuest, global::GooglePlayGames.BasicApi.Quests.IQuestMilestone> callback)
		{
			global::GooglePlayGames.OurUtils.Misc.CheckNotNull(milestone);
			global::GooglePlayGames.OurUtils.Misc.CheckNotNull(callback);
			callback = global::GooglePlayGames.Native.CallbackUtils.ToOnGameThread(callback);
			global::GooglePlayGames.Native.PInvoke.NativeQuestMilestone nativeQuestMilestone = milestone as global::GooglePlayGames.Native.PInvoke.NativeQuestMilestone;
			if (nativeQuestMilestone == null)
			{
				global::GooglePlayGames.OurUtils.Logger.e("Encountered milestone that was not generated by this IQuestClient");
				callback(global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.BadInput, null, null);
				return;
			}
			mManager.ClaimMilestone(nativeQuestMilestone, delegate(global::GooglePlayGames.Native.PInvoke.QuestManager.ClaimMilestoneResponse response)
			{
				if (response.RequestSucceeded())
				{
					callback(global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.Success, response.Quest(), response.ClaimedMilestone());
				}
				else
				{
					callback(FromClaimStatus(response.ResponseStatus()), null, null);
				}
			});
		}

		private static global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus FromClaimStatus(global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestClaimMilestoneStatus status)
		{
			switch (status)
			{
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestClaimMilestoneStatus.VALID:
				return global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.Success;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestClaimMilestoneStatus.ERROR_INTERNAL:
				return global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.InternalError;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestClaimMilestoneStatus.ERROR_MILESTONE_ALREADY_CLAIMED:
				return global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.MilestoneAlreadyClaimed;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestClaimMilestoneStatus.ERROR_MILESTONE_CLAIM_FAILED:
				return global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.MilestoneClaimFailed;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestClaimMilestoneStatus.ERROR_NOT_AUTHORIZED:
				return global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.NotAuthorized;
			case global::GooglePlayGames.Native.Cwrapper.CommonErrorStatus.QuestClaimMilestoneStatus.ERROR_TIMEOUT:
				return global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.Timeout;
			default:
				global::GooglePlayGames.OurUtils.Logger.e("Encountered unknown status: " + status);
				return global::GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.InternalError;
			}
		}
	}
}
